#define LOG_LEVEL_NOOUTPUT 0
#define LOG_LEVEL_ERRORS 1
#define LOG_LEVEL_INFOS 2
#define LOG_LEVEL_DEBUG 3
#define LOG_LEVEL_VERBOSE 4

//#define LOGLEVEL LOG_LEVEL_NOOUTPUT
//#define LOGLEVEL LOG_LEVEL_ERRORS
//#define LOGLEVEL LOG_LEVEL_INFOS
#define LOGLEVEL LOG_LEVEL_DEBUG
//#define LOGLEVEL LOG_LEVEL_VERBOSE
